language: node_js
node_js:
- '6'
script: npm run build
deploy:
  provider: heroku
  api_key:
    secure: rbmcSQ7EV5a7UPueg5i7DbInFQi3BoBRqsuaW/d8V97t36MTZS7SvxMv3bsaeATUTGV+fwgjbSoO4D+LlS9tyu6pMKbXW6bI4xyX43c6RbnH+JTKQUuBtu/nORsQ5y53h0JHVkgycZxwOihcDxa8k0UvuHq3eGHH9ksh8pjlRwddkQ/hC0mSBOaj5DBne59arF+Ml/NTQae4ZEPJBnEq9ViRrMUBMWcTux2Lr4O7btRUPvGZuIMo0DdKmB7nJz2u9nwbkM/pwR5Q59Mt4E2IGHBjzPKzWNrA6BJID8Ptniw5EruTG6NgbTZWq7G1EL7zDcuZqn8NzvCVUX0hiJCajEdqFD9TtjI2MaQlWSNmOBy+1VqkOZbN78hnbTRTtH6ghX9CIfrKmfTVygPjNh0kdj/3wK0Vl76S6oT5VsqnVDM+Zwoxi9g2NNtkvRzZEcXwjjBThlMYpQu691kaKoB0/uRS+YE9bribpUp6HOYTxBu69BnpN1kQpmYcJ2oM5mWp7EDKGZZxzNSOXkCGB2UvZynBhQ9+8gT7pkkDKtR4R3pNF2UfTXcluDjYhrIXPFy5gM8xv7orEYV/pl1j+o5z2KjTtKtKWjJt977fVhB1XO0mweLDjmpTjMQSily9hF1D2bQJaXwPepGmo+iiduPf+Joz/CxS4E3xqcpnzfSrdRw=
  app: pdp-travis-ci
  skip_cleanup: true